[server]
port = 8080

[database]
name = "starkship_server"
connection_string = "xxxxxx"

[nft_contract]
address = "0xXXXXXXXXXXXX"
private_key = "1"

[starknetid_contracts]
naming_contract = "0xXXXXXXXXXXXX"
verifier_contract = "0xXXXXXXXXXXXX"
identity_contract = "0xXXXXXXXXXXXX"

[quests]
starkfighter_server = "https://server.starkfighter.xyz/"
utils_contract = "0xXXXXXXXXXXXX"

[variables]
app_link = "https://starknet.quest"
is_testnet = false
proxy = "xxxxx"