[server]
port = 8080

[database]
name = "starkship_server"
connection_string = "xxxxxx"

[nft_contract]
address = "0xXXXXXXXXXXXX"
private_key = "1"

[starknetid_contracts]
naming_contract = "0xXXXXXXXXXXXX"
verifier_contract = "0xXXXXXXXXXXXX"
identity_contract = "0xXXXXXXXXXXXX"

[quests]
[quests.starkfighter]
server = "https://server.starkfighter.xyz/"
[quests.jediswap]
utils_contract = "0xXXXXXXXXXXXX"
pairs = ["0xXXXXXXXXXXXX"]
tweet_id = "123"
[quests.starknetid]
account_id = "1558813489048829959"
[quests.sithswap]
utils_contract = "0xXXXXXXXXXXXX"
pairs = ["0xXXXXXXXXXXXX"]
tweet_id = "123"

[twitter]
oauth2_clientid = "xxxxxx"
oauth2_secret = "xxxxxx"

[discord]
oauth2_clientid = "xxxxxx"
oauth2_secret = "xxxxxx"

[variables]
app_link = "https://starknet.quest"
api_link = "https://api.starknet.quest"
is_testnet = false
proxy = "xxxxx"
