[server]
port = 8080

[database]
name = "starkship_server"
connection_string = "xxxxxx"

[nft_contract]
address = "0xXXXXXXXXXXXX"
private_key = "1"

[starknetid_contracts]
naming_contract = "0xXXXXXXXXXXXX"
verifier_contract = "0xXXXXXXXXXXXX"
identity_contract = "0xXXXXXXXXXXXX"

[quests]
[quests.sithswap]
utils_contract = "0xXXXXXXXXXXXX"
pairs = ["0xXXXXXXXXXXXX"]
[quests.jediswap]
utils_contract = "0xXXXXXXXXXXXX"
pairs = ["0xXXXXXXXXXXXX"]
[quests.zklend]
contract = "0xXXXXXXXXXXXX"
[quests.ekubo]
contract = "0xXXXXXXXXXXXX"
[quests.myswap]
contract = "0xXXXXXXXXXXXX"
[quests.braavos]
api_key_user = "xxxxxx"
api_key_claimed_mission = "xxxxxx"

[twitter]
oauth2_clientid = "xxxxxx"
oauth2_secret = "xxxxxx"

[discord]
oauth2_clientid = "xxxxxx"
oauth2_secret = "xxxxxx"

[variables]
app_link = "https://starknet.quest"
api_link = "https://api.starknet.quest"
is_testnet = false
rpc_url = "xxxxx"

[starkscan]
api_key = "xxxxxx"

[achievements]
[achievements.braavos]
contract = "0x00057c4b510d66eb1188a7173f31cccee47b9736d40185da8144377b896d5ff3"
[achievements.argent]
contract = "0x01b22f7a9d18754c994ae0ee9adb4628d414232e3ebd748c386ac286f86c3066"
[achievements.carbonable]
contract = "0x0541b5dd5fae206ceccaf4eeb0642e4c04d456c5bc296eab047c9414bdad4f09"

[quizzes]

[quizzes.ekubo]
name = "Ekubo Quiz"
desc = "Challenge your knowledge of Ekubo with our quiz for a chance to secure an exclusive NFT as your reward"
intro = "Welcome to the Ekubo quiz. Let's begin. We hope you're as concentrated as the concentrated liquidity that Ekubo provides. Good Luck!"

[[quizzes.ekubo.questions]]
kind = "text_choice"
layout = "default"
question = "Where is Ekubo building its platform?"
options = ["BSC", "Solana", "Starknet", "Ethereum"]
correct_answers = [*]

[[quizzes.ekubo.questions]]
kind = "text_choice"
layout = "default"
question = "What are the key features of the Ekubo Protocol?"
options = [
    "Decentralization and security", 
    "Concentrated liquidity, a singleton architecture, and extensions", 
    "High transaction fees", 
    "Limited liquidity options"
]
correct_answers = [*]

[[quizzes.ekubo.questions]]
kind = "text_choice"
layout = "default"
question = "What benefits come with concentrated liquidity?"
options = [
    "It limits liquidity provider choices", 
    "It increases transaction fees", 
    "It offers better pricing due to leverage within a price range", 
    "It restricts liquidity providers from earning yield"
]
correct_answers = [*]

[quizzes.morphine]
name = "Morphine Quiz"
desc = "Test your Morphine knowledge in our quiz for a chance to win an exclusive NFT as your reward."
intro = "Welcome to the Morphine quiz! Are you familiar with DeFi on Morphine? Let's explore it together. Good luck!"

[[quizzes.morphine.questions]]
kind = "text_choice"
layout = "default"
question = "How do Morphine vaults earn extra yield?"
options = [
    "Liquidity mining", 
    "Interest auto-compounding", 
    "Intelligent liquidity management", 
    "Debt reallocation"
]
correct_answers = [*]

[[quizzes.morphine.questions]]
kind = "text_choice"
layout = "default"
question = "Which yield is the best to target on morphine?"
options = [
    "Yield with high TVL and low fees", 
    "Yield with high TVL and high fees", 
    "Yield with low TVL and low fees", 
    "Yield with low TVL and high fees"
]
correct_answers = [*]

[[quizzes.morphine.questions]]
kind = "text_choice"
layout = "default"
question = "What is the value of Morphine?"
options = [
    "Comparing all yields to find best yield", 
    "Providing lending interest", 
    "Swapping assets", 
    "Bridging funds"
]
correct_answers = [*]

[quizzes.carmine]
name = "Carmine Quiz"
desc = "Test your knowledge of Carmine Options in our quiz, and you could win an exclusive NFT as your prize."
intro = "Welcome to the Carmine Options quiz. Are you an options expert? Let's discover together. Best of luck!"

[[quizzes.carmine.questions]]
kind = "text_choice"
layout = "default"
question = "Which financial product does Carmine offer?"
options = [
    "Options", 
    "FX", 
    "Forwards", 
    "Ethereum"
]
correct_answers = [*]

[[quizzes.carmine.questions]]
kind = "text_choice"
layout = "default"
question = "What are call options?"
options = [
    "A type of smart contract to execute trades", 
    "A financial contract that gives the holder the right to buy a specific stock at a specified price within a certain time frame", 
    "A method for making efficient trading", 
    "A derivative to settle in the present time"
]
correct_answers = [*]

[[quizzes.carmine.questions]]
kind = "text_choice"
layout = "default"
question = "What is the role of liquidity providers in Carmine Option liquidity pools?"
options = [
    "Liquidity providers facilitate options trades", 
    "Liquidity providers update volatility mechanisms", 
    "Liquidity providers assume the counter-position to users' options trades", 
    "Liquidity providers enforce exposure limits"
]
correct_answers = [*]

[quizzes.gigabrain]
name = "Starknet Giga Brain Quiz"
desc = "Starknet Quest Quiz Rounds, a quiz series designed to make Starknet ecosystem knowledge accessible and enjoyable for all. Test your knowledge, have fun, and earn exclusive NFT rewards by testing your Starknet related topics."
intro = "Starknet Quest Quiz Rounds, a quiz series designed to make Starknet ecosystem knowledge accessible and enjoyable for all. Test your knowledge, have fun, and earn exclusive NFT rewards by testing your Starknet related topics."

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What is Starknet?"
options = [
    "Starknet is a zkEVM scaling solution.", 
    "Starknet is a Layer 1 blockchain separate from Ethereum.", 
    "An Ethereum Layer 2 secured by STARK proofs.", 
    "Starknet is a permissioned blockchain primarily used for private business logic."
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What are STARKs?"
options = [
    "STARKs is a cryptographic solution decreasing blockspace.", 
    "STARKs are a mathematical mechanism to provide proof of integrity in computer tasks.", 
    "STARKs are a widely adopted consensus algorithm for blockchain networks.", 
    "STARKs are a collection of Smart contract execution models."
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What are the differences between SNARKs and STARKs in the context of rollups?"
options = [
    "SNARKs are more scalable and require no trusted setup, while STARKs are vulnerable to quantum computers", 
    "SNARKs require a trusted setup and are less scalable, while STARKs are secure against quantum computers and offer more scalability.", 
    "SNARKs and STARKs are two names for the same cryptographic technique with no differences.", 
    "SNARKs are faster to generate and verify than STARKs, but STARKs are more widely adopted in the blockchain industry."
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "Which one of these 4 options plays a crucial in Starknets architecture? "
options = [
    "Miner",
    "Executor",
    "Sequencer",
    "Interpreter"
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What is Cairo?"
options = [
    "Cairo is a low-level assembly language.",
    "Cairo is a provable programming language that permits to deploy smart contracts on Starknet.",
    "Cairo is a blockchain platform for deploying smart contracts.",
    "Cairo is a Rust-based virtual machine."
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What is the primary role of the Starknet Foundation within the ecosystem?"
options = [
    "To serve as a mission-driven non-profit organization.",
    "To maintain Starknet as a permissioned infrastructure.",
    "To advance decentralization goals, liveness, censorship-resistance, transparency, and creativity within Starknet.",
    "To make decisions regarding protocol updates and dispute resolution informally without any defined process."
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "How does the voting process work on Starknet?"
options = [
    "Voting takes place on the Mainnet, and a proposal requires a minimum quorum to be valid.",
    "Voting has a period where voters can examine a proposal and then vote via Snapshot.",
    "The Foundation does the voting process.",
    "Voting power was distributed solely among all DEFI Platforms."
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What will the STRK token be used for?"
options = [
    "Transaction fees, staking, and voting in Starknet governance.",
    "Solely for paying transaction fees in Ether (ETH).",
    "To secure the network and ensure its liveness.",
    "To support the development of non-native tokens within Starknet."
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What are the five committees established by the Starknet Foundation?"
options = [
    "Infrastructure Committee, Innovation Committee, Community Committee, Funding Committee, Security Committee",
    "Development Committee, Compliance Committee, Stakeholder Committee, Advisory Committee, Network Committee ",
    "Provisions Committee, Early Adopter Grants Committee, Developer Partnerships Committee, Governance Committee, Ecosystem Onboarding Committee",
    "Protocol Committee, Foundation Committee, Security Committee, Validators Committee, Stakeholder Engagement Committee"
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What does SNIP stand for in the context of Starknet?"
options = [
    "Starknet Networking and Infrastructure Protocol",
    "Starknet Improvement Protocol",
    "Starknet Node Integration Platform",
    "Starknet Security and Identity Protocol"
]
correct_answers = [*]

[[quizzes.gigabrain.questions]]
kind = "text_choice"
layout = "default"
question = "What was the Quantum Leap upgrade and what did it achieve?"
options = [
    "A Starknet upgrade which achieved a 10X increase in Tps.",
    "An upgrade of Starknet Beta V1.0.0, and introduced a new scripting language.",
    "An upgrade of Starknet V.0.11.9 and it achieved security enhancements.",
    "Starknet upgraded which achieved 10x transaction latency."
]
correct_answers = [*]