[server]
port = 8080

[database]
name = "starkship_server"
connection_string = "xxxxxx"

[nft_contract]
address = "0xXXXXXXXXXXXX"
private_key = "1"

[starknetid_contracts]
naming_contract = "0xXXXXXXXXXXXX"
verifier_contract = "0xXXXXXXXXXXXX"
identity_contract = "0xXXXXXXXXXXXX"

[quests]
[quests.sithswap]
utils_contract = "0xXXXXXXXXXXXX"
pairs = ["0xXXXXXXXXXXXX"]
[quests.jediswap]
utils_contract = "0xXXXXXXXXXXXX"
pairs = ["0xXXXXXXXXXXXX"]
[quests.zklend]
contract = "0xXXXXXXXXXXXX"
[quests.ekubo]
utils_contract = "0xXXXXXXXXXXXX"
pairs = ["0xXXXXXXXXXXXX"]

[twitter]
oauth2_clientid = "xxxxxx"
oauth2_secret = "xxxxxx"

[discord]
oauth2_clientid = "xxxxxx"
oauth2_secret = "xxxxxx"

[variables]
app_link = "https://starknet.quest"
api_link = "https://api.starknet.quest"
is_testnet = false
proxy = "xxxxx"

[starkscan]
api_key = "xxxxxx"

[achievements]
[achievements.braavos]
contract = "0x00057c4b510d66eb1188a7173f31cccee47b9736d40185da8144377b896d5ff3"
[achievements.argent]
contract = "0x01b22f7a9d18754c994ae0ee9adb4628d414232e3ebd748c386ac286f86c3066"

[quizzes]

[quizzes.ekubo]
name = "Ekubo Quiz"
desc = "Test your knowledge with our example quiz."
intro = "Welcome to this example quiz. Let's get started."

[[quizzes.ekubo.questions]]
kind = "text_choice"
layout = "default"
question = "Where is Ekubo building its platform?"
options = [[****]]
correct_answers = [*]

[[quizzes.ekubo.questions]]
kind = "text_choice"
layout = "default"
question = "What are the key features of the Ekubo Protocol?"
options = [****]
correct_answers = [*]

[[quizzes.ekubo.questions]]
kind = "text_choice"
layout = "default"
question = "What benefit does concentrated liquidity provide to swappers?"
options = [****]
correct_answers = [*]

[[quizzes.ekubo.questions]]
kind = "text_choice"
layout = "default"
question = "What additional action can market makers perform on Ekubo?"
options = [****]
correct_answers = [*]
