version: '3'

services:

  game-server:
    container_name: game-server
    build: .
    command: ./target/release/game-server
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'server.starknet.quest'
      SITES: 'server.starknet.quest=game-server:8080'

volumes:
  ssl_data:
