version: "3"

services:
  quest_server:
    container_name: quest_server
    build: .
    command: ./target/release/quest_server
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "api.starknet.quest"
      SITES: "api.starknet.quest=quest_server:8080"

volumes:
  ssl_data:
